"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider, createTheme } from "@mui/material";
import NavBar from "@/components/ui/Navbar";

const theme = createTheme({
  palette: {
    primary: {
      main: "#8DAEF6",
    },
    secondary: {
      main: "#e4d0a2",
    },
  },
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ThemeProvider theme={theme}>
      <html lang="en">
        <body className={inter.className}>
          <NavBar />
          {children}
        </body>
      </html>
    </ThemeProvider>
  );
}
